"""add cases and audit

Revision ID: 68ececa9f021
Revises: c373b3193e2e
Create Date: 2026-05-14 21:48:05.966920
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '68ececa9f021'
down_revision: Union[str, None] = 'c373b3193e2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
