"""add cases and audit

Revision ID: c373b3193e2e
Revises: f7f39b40cdcf
Create Date: 2026-05-14 21:37:38.919299
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c373b3193e2e'
down_revision: Union[str, None] = 'f7f39b40cdcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
