"""add cases and audit

Revision ID: f7f39b40cdcf
Revises: 7dd1e2919b8b
Create Date: 2026-05-14 21:31:22.350171
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'f7f39b40cdcf'
down_revision: Union[str, None] = '7dd1e2919b8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.String(length=100), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patient_cases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.String(length=100), nullable=False),
    sa.Column('patient_name', sa.String(length=255), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('sex', sa.String(length=10), nullable=True),
    sa.Column('clinical_history', sa.Text(), nullable=True),
    sa.Column('priority', sa.Enum('ROUTINE', 'URGENT', 'STAT', name='casepriority'), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'REPORTED', 'CLOSED', name='casestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_cases_patient_id'), 'patient_cases', ['patient_id'], unique=False)
    op.add_column('medical_images', sa.Column('case_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'medical_images', 'patient_cases', ['case_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'medical_images', type_='foreignkey')
    op.drop_column('medical_images', 'case_id')
    op.drop_index(op.f('ix_patient_cases_patient_id'), table_name='patient_cases')
    op.drop_table('patient_cases')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
